### ISSUE TITLE
success stories in bug reporting

### ISSUE THREAD

**Issue by tdhock** [forwards/rdevguide#12]
hi @SaranjeetKaur @hturner during the call today somebody mentioned the possibility of sharing success stories in reporting bugs to R-devel. Here are a couple of positive examples from my experience
- [substring bug reported by Toby Dylan Hocking and fixed by Tomas Kalibera, Feb 2019](https://stat.ethz.ch/pipermail/r-devel/2019-February/077393.html)
- [gregexpr bug report and patch submitted by Toby Dylan Hocking and merged by Tomas Kalibera, Feb 2019](https://stat.ethz.ch/pipermail/r-devel/2019-February/077315.html)

take home messages:
- both of these resulted in fixes to R 
- both happened only on R-devel email list (neither required posting to bugzilla)
- if you can, post a patch which fixes the problem
- otherwise, just describe the problem and hopefully somebody in R-core will investigate and fix

**Comment by SaranjeetKaur** [comment]
Thanks for sharing this @tdhock! The examples are now included in the Bug Reporting chapter (chapter 3).

**Comment by tdhock** [comment]
great! glad that helped!
